package com.lec.ex2_throws;

public class ThrowsEx {  //Main에서 이 class를 호출했다
	public ThrowsEx() {
		actionC(); //class안에서 actionC호출 
	}
	private void actionC() {  //class안에서만 사용
		System.out.println("actionC 전반부");
		actionB();
		System.out.println("actionC 후반부");
	}
	private void actionB() {
		System.out.println("actionB 전반부");
		actionA();
		System.out.println("actionB 후반부");
	}
	private void actionA() {
		System.out.println("action A 전반부");
		int[] arr = {0,1,2,3};
		try {
			System.out.println(arr[4]); //Exception   4번방이 존재하지 않기 떄문에
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println(e.getMessage());
		}
		System.out.println("actionA 후반부");
	}
}
